# Generated by Django 6.0.2 on 2026-02-11 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.CharField(max_length=60)),
                ('mmr', models.IntegerField(blank=True, db_index=True, null=True)),
                ('wins', models.IntegerField(blank=True, null=True)),
                ('losses', models.IntegerField(blank=True, null=True)),
                ('steam_id', models.CharField(blank=True, max_length=60, null=True)),
                ('steam_community', models.URLField(blank=True, null=True)),
                ('region', models.IntegerField(choices=[(1, 'North America'), (2, 'South America'), (3, 'Europe'), (4, 'Asia'), (5, 'Africa'), (6, 'Australia')], db_index=True, default=1)),
                ('looking_for_team', models.BooleanField(default=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('preferred_roles', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-mmr'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('image', models.ImageField(default='default.png', upload_to='team_pics')),
                ('interests', models.IntegerField(choices=[(1, 'Battle Cup'), (2, 'Leagues'), (3, 'MatchMaking'), (4, 'Casual Play')])),
                ('region', models.IntegerField(choices=[(1, 'North America'), (2, 'South America'), (3, 'Europe'), (4, 'Asia'), (5, 'Africa'), (6, 'Australia')], db_index=True, default=1)),
                ('looking_for_members', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=250)),
                ('role', models.CharField(choices=[('Carry', 'Hard Carry'), ('Mid', 'Mid Lane'), ('Offlane', 'Offlaner'), ('Support', 'Soft Support'), ('Hard Support', 'Hard Support')], max_length=20)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected')], db_index=True, default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='api.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='api.team')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('team', 'player')},
            },
        ),
        migrations.CreateModel(
            name='TeamInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(choices=[('Carry', 'Hard Carry'), ('Mid', 'Mid Lane'), ('Offlane', 'Offlaner'), ('Support', 'Soft Support'), ('Hard Support', 'Hard Support')], max_length=20)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected')], db_index=True, default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invites', to='api.player')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invites', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='api.team')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('team', 'recipient')},
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Carry', 'Hard Carry'), ('Mid', 'Mid Lane'), ('Offlane', 'Offlaner'), ('Support', 'Soft Support'), ('Hard Support', 'Hard Support')], max_length=20)),
                ('is_captain', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='api.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='api.team')),
            ],
            options={
                'ordering': ['joined_at'],
                'unique_together': {('team', 'player')},
            },
        ),
    ]
