# Generated by Django 6.0.2 on 2026-02-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='persona',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
