# Generated by Django 6.0.2 on 2026-02-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_player_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='steam_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='interests',
            field=models.IntegerField(choices=[(1, 'Battle Cup'), (2, 'Leagues'), (3, 'MatchMaking'), (4, 'Casual Play')], default=3),
        ),
        migrations.AlterField(
            model_name='team',
            name='region',
            field=models.IntegerField(choices=[(1, 'North America'), (2, 'South America'), (3, 'Europe'), (4, 'Asia'), (5, 'Africa'), (6, 'Australia')], db_index=True, default=3),
        ),
    ]
