# Generated by Django 6.0.2 on 2026-02-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_player_steam_verified_alter_team_interests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='mmr',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
