# Generated by Django 6.0.2 on 2026-02-16 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_team_mmr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-mmr', '-created_at']},
        ),
    ]
