# Generated by Django 6.0.2 on 2026-02-16 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_team_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='team',
            name='mmr',
        ),
    ]
