# Generated by Django 6.0.2 on 2026-03-06 22:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_team_options_remove_team_mmr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teaminvite',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='teammembership',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='teaminvite',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 1)), fields=('team', 'recipient'), name='unique_pending_invite'),
        ),
        migrations.AddConstraint(
            model_name='teaminvite',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 1)), fields=('team', 'role'), name='unique_pending_role_invite'),
        ),
        migrations.AddConstraint(
            model_name='teammembership',
            constraint=models.UniqueConstraint(fields=('team', 'player'), name='unique_team_player'),
        ),
        migrations.AddConstraint(
            model_name='teammembership',
            constraint=models.UniqueConstraint(fields=('team', 'role'), name='unique_team_role'),
        ),
        migrations.AddConstraint(
            model_name='teammembership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_captain', True)), fields=('team',), name='one_captain_per_team'),
        ),
    ]
