# Generated by Django 6.0.2 on 2026-03-07 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_teaminvite_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teamapplication',
            unique_together=set(),
        ),
    ]
