# Generated by Django 6.0.2 on 2026-03-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_teamapplication_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='top_heroes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
